### ISSUE TITLE
Investigation into data from OpenZaak

### ISSUE THREAD

**Issue by mjcarsjens** [Gemeente-DenHaag/mijndenhaag-pwa#10]
## Openzaak information and documentation

Documentation about OpenZaak kan be found at: [https://open-zaak.readthedocs.io/](https://open-zaak.readthedocs.io/).

OpenZaak is an implementation of the Zaakgericht Werken API specifications of the VNG created by Maykin Media. 

OpenZaak implements the following specifications:

- Zaken API | 1.0
- Documenten API | 1.0
- Catalogi API | 1.0
- Besluiten API | 1.0
- Autorisaties API | 1.0

Our OpenZaak Test environment can be found at https://open-zaak.ot.denhaag.nl/
Authorization for this API happens with a JWT token generated from a client_id and a secret. These have to be added in the Admin interface of OpenZaak.

Each client_id (authorized application) can be given access to several different authorization rules, which very specifically state which API endpoints the application can access, and whether this is read-only or also write access (to create a new Zaak).

## What do we want to achieve?

For this story we will begin by focussing on the Zaken API: [https://open-zaak.ot.denhaag.nl/zaken/api/v1/schema/](https://open-zaak.ot.denhaag.nl/zaken/api/v1/schema/), but we might also need the others depending on what we want to show.

We want to be able to retrieve the data from OpenZaak to show an overview of Zaken and to show the details of a specific Zaak. 
For this we will need the following two endpoints:

Overview of zaken: [https://open-zaak.ot.denhaag.nl/zaken/api/v1/zaken](https://open-zaak.ot.denhaag.nl/zaken/api/v1/zaken)
Details of a specific zaak: [https://open-zaak.ot.denhaag.nl/zaken/api/v1/zaken/{uuid}](https://open-zaak.ot.denhaag.nl/zaken/api/v1/zaken/{uuid})

For our initial research we want to have an overview of what data we need to show all the information for a Zaak currently in the designs.

Overview design: [https://www.figma.com/proto/UavWwPqFfBgGQqFbeGgJgW/Prototype-%2301---Ons-Den-Haag?node-id=909%3A13510&viewport=1427%2C212%2C0.07503892481327057&scaling=min-zoom&hide-ui=1](Figma)

Detail design: [https://www.figma.com/proto/UavWwPqFfBgGQqFbeGgJgW/Prototype-%2301---Ons-Den-Haag?node-id=909%3A13510&viewport=1427%2C212%2C0.07503892481327057&scaling=min-zoom&hide-ui=1](Figma)
 
In short: our goal for this story is to create an overview of which fields of the Zaken API are relevant to us to show the data we want to show, which data do we need to retrieve from the other API's and furthermore, which data is currently absent in/not supported by OpenZaak.

### Playing around with the API
To play around with the API itself which might be helpful besides all the information I suggest the following tool:
- Postman to make API calls

***API test with Postman: Requirements***
- Credentials (client_id and secret) for OpenZaak
- a (test) Person in OpenZaak with actual Zaken assigned to them
- The (test) BSN corresponding to this Person to retrieve their Zaken

***API test with Postman: Steps***
- Open Postman 
- Start With Something New -> Click 'Create New'
- Click 'Create a Request'
- Enter `https://open-zaak.ot.denhaag.nl/zaken/api/v1/zaken` in the Request URL field
- Under params add a param with key `rol__betrokkeneIdentificatie__natuurlijkPersoon__inpBsn` and as value the BSN of the person
- Generate a JWT token for the clientId and secret (example: [https://jwt.io/](https://jwt.io/), below you can choose an library of your choice) (see API docs for what needs to be in the JWT token)
- Under the Authorization tab Choose Type 'Bearer Token' and enter the JWT token
- Under Headers enter two headers: `Accept-Crs` and `Content-Crs` both with value: `EPSG:4326`

## Tasks
- [x] Read documentation from OpenZaak API
- [x] Retrieve client ID and secret to use the endpoint
- [x] Play around using Postman to get a general feel about the API
- [x] Identify and document the API data we need to show the `Zaken` overview 
- [x] Identify and document the API data we need to show the `Zaak` detail page, and document what fields are still missing in the API

**Comment by bddjong** [comment]
https://open-zaak.readthedocs.io/en/latest/client-development/authentication.html
