### ISSUE TITLE
As a citizen/entrepeneur I can see the details of a 'Zaak'

### ISSUE THREAD

**Issue by mjcarsjens** [Gemeente-DenHaag/mijndenhaag-pwa#11]
When a specific 'Zaak' is clicked in the overview of 'Mijn Zaken' a detail view should appear showing the details corresponding to the clicked 'Zaak'. This data is retrieved from the 'OpenZaak' API.

For now we want to display the following components from the [figma design](https://www.figma.com/proto/UavWwPqFfBgGQqFbeGgJgW/Prototype-%2301---Ons-Den-Haag?node-id=912%3A238&viewport=1427%2C212%2C0.07503892481327057&scaling=min-zoom&hide-ui=1):

- Back button and title
- General case information
- Status block
- Chat block (scope adjusted from design, see story #12 )
- Documenten block
- Kosten block

**TODO**: Add issue numbers for the individual issues of the components as stated above.

**Acceptationcriteria**
- [ ] Adheres to the current Figma designs (see expection on #12 ) for components named above
- [ ] Show details from example zaken from OpenZaak via tasklibrary.
- [ ] Zaak Details is reached via Zaken Overzicht Page
- [ ] This is build as a seperate component
- [ ] An other municipality can use the overview within it's own portal and can use own 'cards' or e.g. table
